const ADMISSIBLE_SHORT_OPTIONS = ['s', 'a'];
const ADMISSIBLE_LONG_OPTIONS = ['shift', 'action'];

exports.ADMISSIBLE_SHORT_OPTIONS = ADMISSIBLE_SHORT_OPTIONS;
exports.ADMISSIBLE_LONG_OPTIONS = ADMISSIBLE_LONG_OPTIONS;