const ADMISSIBLE_SHORT_OPTIONS = ['s', 'a'];
const ADMISSIBLE_LONG_OPTIONS = ['shift', 'action'];

const ACTION_TYPES = ['encode', 'decode'];

exports.ADMISSIBLE_SHORT_OPTIONS = ADMISSIBLE_SHORT_OPTIONS;
exports.ADMISSIBLE_LONG_OPTIONS = ADMISSIBLE_LONG_OPTIONS;
exports.ACTION_TYPES = ACTION_TYPES;